### ISSUE TITLE
plz open source messages wrapped!

### ISSUE THREAD

**Issue by alii** [3eif/messages-wrapped-releases#2]
Not really willing to run the app without reading/building from source, would be great if we could do that!

**Comment by 3eif** [comment]
Sorry, no plans to open source it.

**Comment by 3eif** [comment]
I can assure you it's completely safe to run. You can read about how we handle your data here: https://messageswrapped.com/legal/privacy

**Comment by alii** [comment]
No worries, and understood. thanks! :)
